FROM node:16.14.2 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/App
RUN yarn install && yarn testV2

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/App/build .
COPY nginx.conf /etc/nginx/nginx.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]