export interface styleItemType {
    id: string;
    cover: string;
    style: string;
    title: string;
}

export const ChinaStyleOverviewList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWkSa.png',
        //cover: bg_ChinaStyle_01,
        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWsql.png',
        //cover: bg_ChinaStyle_02,
        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWAor.png',
        //cover: bg_ChinaStyle_03,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWd6v.png',
        //cover: bg_ChinaStyle_04,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWCvH.png',
        //cover: bg_ChinaStyle_05,
        style: 'China',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWv8Z.png',
        //cover: bg_ChinaStyle_06,
        style: 'China',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWIF6.png',
        //cover: bg_ChinaStyle_07,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWKbA.png',
        //cover: bg_ChinaStyle_08,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWlV4.png',
        //cover: bg_ChinaStyle_09,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWyOE.png',
        //cover: bg_ChinaStyle_10,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWSSg.png',
        //cover: bg_ChinaStyle_11,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWwoU.png',
        //cover: bg_ChinaStyle_12,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWpBx.png',
        //cover: bg_ChinaStyle_13,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWUvX.png',
        //cover: bg_ChinaStyle_14,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
];
export const gameStyleOverviewList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWbR2.png',
        //cover: bg_gameStyle_01,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CW08S.png',
        //cover: bg_gameStyle_02,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWEFu.png',
        //cover: bg_gameStyle_03,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWQ0q.png',
        //cover: bg_gameStyle_04,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZ6Xh.png',
        //cover: bg_gameStyle_05,
        style: 'game',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CWMVK.png',
        //cover: bg_gameStyle_06,
        style: 'game',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZRj1.png',
        //cover: bg_gameStyle_07,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZ5BG.png',
        //cover: bg_gameStyle_08,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZHrP.png',
        //cover: bg_gameStyle_09,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZnvT.png',
        //cover: bg_gameStyle_10,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZBRF.png',
        //cover: bg_gameStyle_11,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZaPD.png',
        //cover: bg_gameStyle_12,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZfFb.png',
        //cover: bg_gameStyle_13,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZ20N.png',
        //cover: bg_gameStyle_14,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
];
export const tecStyleOverviewList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZ7x7.png',
        //cover: bg_tecStyle_01,
        style: 'tec',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZVXp.png',
        //cover: bg_tecStyle_02,
        style: 'tec',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZxjL.png',
        //cover: bg_tecStyle_03,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZDaa.png',
        //cover: bg_tecStyle_04,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZJrl.png',
        //cover: bg_tecStyle_05,
        style: 'tec',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZ4Ir.png',
        //cover: bg_tecStyle_06,
        style: 'tec',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZWPv.png',
        //cover: bg_tecStyle_07,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZP1H.png',
        //cover: bg_tecStyle_08,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZmE6.png',
        //cover: bg_tecStyle_09,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZZsZ.png',
        //cover: bg_tecStyle_10,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZoxA.png',
        //cover: bg_tecStyle_11,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZre4.png',
        //cover: bg_tecStyle_12,
        style: 'tec',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZtjE.png',
        //cover: bg_tecStyle_13,
        style: 'tec',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZ9ag.png',
        //cover: bg_tecStyle_14,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '15',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZLtx.png',
        //cover: bg_tecStyle_15,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
];
