export interface styleItemType {
    id: string;
    cover: string;
    style: string;
    title: string;
}

export const ChinaStyleDetailList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CG8Fb.png',

        // cover: bg_ChinaStyle_01,
        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCq3L.png',
        //cover: bg_ChinaStyle_02,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCBLa.png',
        //cover: bg_ChinaStyle_03,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCall.png',
        //cover: bg_ChinaStyle_04,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CC2nr.png',
        //cover: bg_ChinaStyle_05,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CC3hH.png',
        //cover: bg_ChinaStyle_06,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CC7Gv.png',
        //cover: bg_ChinaStyle_07,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCVMZ.png',
        //cover: bg_ChinaStyle_08,
        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCz46.png',
        //cover: bg_ChinaStyle_09,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCDgA.jpg',
        //cover: bg_ChinaStyle_10,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CC83E.png',
        //cover: bg_ChinaStyle_11,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCJY4.png',
        //cover: bg_ChinaStyle_12,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCPLg.png',
        //cover: bg_ChinaStyle_13,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCWyx.png',
        //cover: bg_ChinaStyle_14,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
];
export const gameStyleDetailList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAyTu.png',
        //cover: bg_gameStyle_01,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAlCS.png',
        //cover: bg_gameStyle_02,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAjJq.png',
        //cover: bg_gameStyle_03,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CApcK.png',
        //cover: bg_gameStyle_04,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAwUh.png',
        //cover: bg_gameStyle_05,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAY31.png',
        //cover: bg_gameStyle_06,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAb9G.png',
        //cover: bg_gameStyle_07,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAQHT.png',
        //cover: bg_gameStyle_08,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CA0lP.png',
        //cover: bg_gameStyle_09,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CATmF.jpg',
        //cover: bg_gameStyle_10,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAMGD.png',
        //cover: bg_gameStyle_11,
        style: 'game',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CC6Tb.png',
        //cover: bg_gameStyle_12,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CC1JN.png',
        //cover: bg_gameStyle_13,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CC5g7.png',
        //cover: bg_gameStyle_14,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
];
export const tecStyleDetailList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CA92a.png',
        //cover: bg_tecStyle_01,
        style: 'tec',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CALul.png',
        //cover: bg_tecStyle_02,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAOir.png',
        //cover: bg_tecStyle_03,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAeHH.png',
        //cover: bg_tecStyle_04,
        style: 'tec',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CANZv.png',
        //cover: bg_tecStyle_05,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAcCZ.png',
        //cover: bg_tecStyle_06,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAgT6.png',
        //cover: bg_tecStyle_07,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAFDA.png',
        //cover: bg_tecStyle_08,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAAwE.png',
        //cover: bg_tecStyle_09,
        style: 'tec',
        title: '点击方块类 - 二位多选',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAsc4.png',
        //cover: bg_tecStyle_10,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAG2g.png',
        //cover: bg_tecStyle_11,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAd9x.png',
        //cover: bg_tecStyle_12,
        style: 'tec',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAviU.png',
        //cover: bg_tecStyle_13,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAKHX.png',
        //cover: bg_tecStyle_14,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '15',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CAim2.png',
        //cover: bg_tecStyle_15,
        style: 'tec',
        title: '拖拽类 - 一维多选',
    },
];
