export interface styleItemType {
    id: string;
    cover: string;
    style: string;
    title: string;
}

export const ChinaStyleOverviewList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmoCF.png',
        //cover: bg_ChinaStyle_01,
        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmrTD.png',
        //cover: bg_ChinaStyle_02,
        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmuDb.png',
        //cover: bg_ChinaStyle_03,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cm9cN.png',
        //cover: bg_ChinaStyle_04,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmLU7.png',
        //cover: bg_ChinaStyle_05,
        style: 'China',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmX2p.png',
        //cover: bg_ChinaStyle_06,
        style: 'China',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cme9L.png',
        //cover: bg_ChinaStyle_07,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmgHl.png',
        //cover: bg_ChinaStyle_08,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmNla.png',
        //cover: bg_ChinaStyle_09,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cmkmr.png',
        //cover: bg_ChinaStyle_10,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmFGH.png',
        //cover: bg_ChinaStyle_11,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmsTv.png',
        //cover: bg_ChinaStyle_12,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmCJZ.png',
        //cover: bg_ChinaStyle_13,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmGg6.png',
        //cover: bg_ChinaStyle_14,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
];
export const gameStyleOverviewList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmdUA.png',
        //cover: bg_gameStyle_01,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmI34.png',
        //cover: bg_gameStyle_02,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmK9E.png',
        //cover: bg_gameStyle_03,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cmilg.png',
        //cover: bg_gameStyle_04,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cmynx.png',
        //cover: bg_gameStyle_05,
        style: 'game',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmSmU.png',
        //cover: bg_gameStyle_06,
        style: 'game',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmjGX.png',
        //cover: bg_gameStyle_07,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmpM2.png',
        //cover: bg_gameStyle_08,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmUJS.png',
        //cover: bg_gameStyle_09,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmYgu.png',
        //cover: bg_gameStyle_10,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmbYq.png',
        //cover: bg_gameStyle_11,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmE3K.png',
        //cover: bg_gameStyle_12,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmQLh.png',
        //cover: bg_gameStyle_13,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmTy1.png',
        //cover: bg_gameStyle_14,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
];
export const tecStyleOverviewList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Ch6nG.png',
        //cover: bg_tecStyle_01,
        style: 'tec',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/03/ChRhP.png',
        //cover: bg_tecStyle_02,
        style: 'tec',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Ch1GT.png',
        //cover: bg_tecStyle_03,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Ch5MF.png',
        //cover: bg_tecStyle_04,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Chn4D.png',
        //cover: bg_tecStyle_05,
        style: 'tec',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Chqgb.png',
        //cover: bg_tecStyle_06,
        style: 'tec',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/03/ChBYN.png',
        //cover: bg_tecStyle_07,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Chf77.png',
        //cover: bg_tecStyle_08,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Ch2Lp.png',
        //cover: bg_tecStyle_09,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Ch3yL.png',
        //cover: bg_tecStyle_10,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/03/ChVqa.png',
        //cover: bg_tecStyle_11,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Chxhl.png',
        //cover: bg_tecStyle_12,
        style: 'tec',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Chzdr.png',
        //cover: bg_tecStyle_13,
        style: 'tec',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/03/ChJ6H.png',
        //cover: bg_tecStyle_14,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '15',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Ch44v.png',
        //cover: bg_tecStyle_15,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
];
