export interface styleItemType {
    id: string;
    cover: string;
    style: string;
    title: string;
}

export const ChinaStyleOverviewList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCTSg.png',
        //cover: bg_ChinaStyle_01,
        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CGRoU.png',
        //cover: bg_ChinaStyle_02,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CG6Bx.png',
        //cover: bg_ChinaStyle_03,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CG1vX.png',
        //cover: bg_ChinaStyle_04,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CGHR2.png',
        //cover: bg_ChinaStyle_05,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CGn8S.png',
        //cover: bg_ChinaStyle_06,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CGqFu.png',
        //cover: bg_ChinaStyle_07,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CGB0q.png',
        //cover: bg_ChinaStyle_08,
        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CGfVK.png',
        //cover: bg_ChinaStyle_09,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CG2Xh.png',
        //cover: bg_ChinaStyle_10,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CGVBG.png',
        //cover: bg_ChinaStyle_11,
        style: 'China',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CG3j1.png',
        //cover: bg_ChinaStyle_12,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CGxrP.png',
        //cover: bg_ChinaStyle_13,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CGzvT.png',
        //cover: bg_ChinaStyle_14,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
];
export const gameStyleOverviewList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCdb7.png',
        //cover: bg_gameStyle_01,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCGkN.png',
        //cover: bg_gameStyle_02,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCI7p.png',
        //cover: bg_gameStyle_03,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCKOL.png',
        //cover: bg_gameStyle_04,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCiSa.png',
        //cover: bg_gameStyle_05,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCyql.png',
        //cover: bg_gameStyle_06,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCSor.png',
        //cover: bg_gameStyle_07,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCw6v.png',
        //cover: bg_gameStyle_08,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCjvH.png',
        //cover: bg_gameStyle_09,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCU8Z.png',
        //cover: bg_gameStyle_10,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCYF6.png',
        //cover: bg_gameStyle_11,
        style: 'game',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCbbA.png',
        //cover: bg_gameStyle_12,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCEV4.png',
        //cover: bg_gameStyle_13,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCQOE.png',
        //cover: bg_gameStyle_14,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
];
export const tecStyleOverviewList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCmnU.png',
        //cover: bg_tecStyle_01,
        style: 'tec',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CChhX.png',

        //cover: bg_tecStyle_02,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCod2.png',

        //cover: bg_tecStyle_03,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCrMS.png',
        //cover: bg_tecStyle_04,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCu4u.png',
        //cover: bg_tecStyle_05,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CC9kq.png',
        //cover: bg_tecStyle_06,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCLYK.png',
        //cover: bg_tecStyle_07,
        style: 'tec',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCX7h.png',
        //cover: bg_tecStyle_08,
        style: 'tec',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCeO1.png',
        //cover: bg_tecStyle_09,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCNyG.png',
        //cover: bg_tecStyle_10,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCgqP.png',
        //cover: bg_tecStyle_11,
        style: 'tec',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCkhT.png',
        //cover: bg_tecStyle_12,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCFdF.png',
        //cover: bg_tecStyle_13,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCC4b.png',
        //cover: bg_tecStyle_14,
        style: 'tec',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '15',
        cover: 'https://s1.imgbed.xyz/2022/11/11/CCA6D.png',
        //cover: bg_tecStyle_15,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
];
