export interface styleItemType {
    id: string;
    cover: string;
    style: string;
    title: string;
}

export const ChinaStyleDetailList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZOIU.png',
        // cover: bg_ChinaStyle_01,

        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZe1X.png',
        //cover: bg_ChinaStyle_02,
        style: 'China',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZNW2.png',
        //cover: bg_ChinaStyle_03,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZcsS.png',
        //cover: bg_ChinaStyle_04,
        style: 'China',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZgEu.png',
        //cover: bg_ChinaStyle_05,
        style: 'China',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZFzq.png',
        //cover: bg_ChinaStyle_06,
        style: 'China',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZseK.png',
        //cover: bg_ChinaStyle_07,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZAph.png',
        //cover: bg_ChinaStyle_08,
        style: 'China',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZGf1.png',
        //cover: bg_ChinaStyle_09,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZdtG.png',
        //cover: bg_ChinaStyle_10,
        style: 'China',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZvKP.png',
        //cover: bg_ChinaStyle_11,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZK1T.png',
        //cover: bg_ChinaStyle_12,
        style: 'China',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZiWF.png',
        //cover: bg_ChinaStyle_13,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZlAD.jpg',
        //cover: bg_ChinaStyle_14,
        style: 'China',
        title: '拖拽类 - 一维圆环打分',
    },
];
export const gameStyleDetailList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZyEb.png',
        //cover: bg_gameStyle_01,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZjzN.png',
        //cover: bg_gameStyle_02,
        style: 'game',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZpN7.png',
        //cover: bg_gameStyle_03,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZwpp.png',
        //cover: bg_gameStyle_04,
        style: 'game',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZbua.png',
        //cover: bg_gameStyle_05,
        style: 'game',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZYfL.png',
        //cover: bg_gameStyle_06,
        style: 'game',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZ0Kl.png',
        //cover: bg_gameStyle_07,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZQ5r.png',
        //cover: bg_gameStyle_08,
        style: 'game',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZTZH.png',
        //cover: bg_gameStyle_09,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CZMAv.png',
        //cover: bg_gameStyle_10,
        style: 'game',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cm6QZ.png',
        //cover: bg_gameStyle_11,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cm1D6.png',
        //cover: bg_gameStyle_12,
        style: 'game',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cm5NA.png',
        //cover: bg_gameStyle_13,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmHw4.jpg',
        //cover: bg_gameStyle_14,
        style: 'game',
        title: '拖拽类 - 一维圆环打分',
    },
];
export const tecStyleDetailList: styleItemType[] = [
    {
        id: '01',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmqfE.png',
        //cover: bg_tecStyle_01,
        style: 'tec',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '02',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmBug.png',
        //cover: bg_tecStyle_02,
        style: 'tec',
        title: '点击方块类 - 二维多选',
    },
    {
        id: '03',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cmaix.png',
        //cover: bg_tecStyle_03,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '04',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cm25U.png',
        //cover: bg_tecStyle_04,
        style: 'tec',
        title: '数字题类 - 一维横向滑块',
    },
    {
        id: '05',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cm3ZX.png',
        //cover: bg_tecStyle_05,
        style: 'tec',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '06',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cm7C2.png',
        //cover: bg_tecStyle_06,
        style: 'tec',
        title: '数字题类 - 一维纵向滑块',
    },
    {
        id: '07',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmVQS.png',
        //cover: bg_tecStyle_07,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '08',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmzDu.png',
        //cover: bg_tecStyle_08,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '09',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmDcq.png',
        //cover: bg_tecStyle_09,
        style: 'tec',
        title: '拖拽类 - 拖拽排序',
    },
    {
        id: '10',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmJwK.png',
        //cover: bg_tecStyle_10,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '11',
        cover: 'https://s1.imgbed.xyz/2022/11/03/Cm82h.png',
        //cover: bg_tecStyle_11,
        style: 'tec',
        title: '拖拽类 - 一维单选',
    },
    {
        id: '12',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmP91.png',
        //cover: bg_tecStyle_12,
        style: 'tec',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '13',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmWiG.png',
        //cover: bg_tecStyle_13,
        style: 'tec',
        title: '拖拽类 - 一维多选',
    },
    {
        id: '14',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmmHP.png',
        //cover: bg_tecStyle_14,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
    {
        id: '15',
        cover: 'https://s1.imgbed.xyz/2022/11/03/CmhZT.png',
        //cover: bg_tecStyle_15,
        style: 'tec',
        title: '拖拽类 - 一维圆环打分',
    },
];
